project:
  type: website
  output-dir: _site_build
  render:
    - index.md
    - about.md
    - analysis.md
    - "!*.qmd"     # 显式排除所有 .qmd，防止 Quarto 去执行 R

website:
  title: "biostat777-intro-yixin-xue"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: about.md
        text: About
      - href: analysis.md
        text: Example analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "On this page"
    toc-depth: 3
    smooth-scroll: true
